# Generated by Django 6.0.1 on 2026-02-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
    ]
