# Generated by Django 6.0.2 on 2026-02-05 05:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kitob Nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Kitob Nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Kitob Nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Kitob Nomi')),
                ('author', models.CharField(max_length=255, verbose_name='Muallif(lar)')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Annotatsiya')),
                ('description_uz', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Annotatsiya')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Annotatsiya')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Annotatsiya')),
                ('category', models.CharField(choices=[('Badiiy', 'Badiiy Adabiyot'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Texnologiya', 'Texnologiya'), ('Diniy', "Diniy-Ma'rifiy"), ('Bolalar', 'Bolalar Adabiyoti'), ('Jahon', 'Jahon Adabiyoti'), ('Barchasi', 'Barchasi')], default='Badiiy', max_length=50, verbose_name='Kategoriya')),
                ('resource_type', models.CharField(choices=[('Kitob', 'Kitob'), ('Avtoreferat', 'Avtoreferat'), ('Monografiya', 'Monografiya'), ("O'quv qo'llanma", "O'quv qo'llanma"), ('Maqola', 'Maqola'), ('Dissertatsiya', 'Dissertatsiya')], default='Kitob', max_length=50, verbose_name='Resurs Turi')),
                ('page_count', models.IntegerField(default=0, verbose_name='Betlar Soni')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Chop Etilgan Sana')),
                ('subjects', models.TextField(help_text='Vergul bilan ajratib yozing: Tarix, Roman, Klassika', verbose_name='Mavzular (Teglar)')),
                ('cover_image', models.ImageField(upload_to='books/covers/', verbose_name='Muqova Rasmi')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/', verbose_name='Kitob Fayli (PDF/EPUB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
