# Generated by Django 6.0.2 on 2026-02-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='books/qrcodes/', verbose_name='QR Kod (Rasm)'),
        ),
    ]
