# Generated by Django 6.0.2 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Muallif(lar)'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Muallif(lar)'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Muallif(lar)'),
        ),
        migrations.AddField(
            model_name='book',
            name='category_en',
            field=models.CharField(choices=[('Badiiy', 'Badiiy Adabiyot'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Texnologiya', 'Texnologiya'), ('Diniy', "Diniy-Ma'rifiy"), ('Bolalar', 'Bolalar Adabiyoti'), ('Jahon', 'Jahon Adabiyoti'), ('Barchasi', 'Barchasi')], default='Badiiy', max_length=50, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='book',
            name='category_ru',
            field=models.CharField(choices=[('Badiiy', 'Badiiy Adabiyot'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Texnologiya', 'Texnologiya'), ('Diniy', "Diniy-Ma'rifiy"), ('Bolalar', 'Bolalar Adabiyoti'), ('Jahon', 'Jahon Adabiyoti'), ('Barchasi', 'Barchasi')], default='Badiiy', max_length=50, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='book',
            name='category_uz',
            field=models.CharField(choices=[('Badiiy', 'Badiiy Adabiyot'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Texnologiya', 'Texnologiya'), ('Diniy', "Diniy-Ma'rifiy"), ('Bolalar', 'Bolalar Adabiyoti'), ('Jahon', 'Jahon Adabiyoti'), ('Barchasi', 'Barchasi')], default='Badiiy', max_length=50, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='book',
            name='resource_type_en',
            field=models.CharField(choices=[('Kitob', 'Kitob'), ('Avtoreferat', 'Avtoreferat'), ('Monografiya', 'Monografiya'), ("O'quv qo'llanma", "O'quv qo'llanma"), ('Maqola', 'Maqola'), ('Dissertatsiya', 'Dissertatsiya')], default='Kitob', max_length=50, null=True, verbose_name='Resurs Turi'),
        ),
        migrations.AddField(
            model_name='book',
            name='resource_type_ru',
            field=models.CharField(choices=[('Kitob', 'Kitob'), ('Avtoreferat', 'Avtoreferat'), ('Monografiya', 'Monografiya'), ("O'quv qo'llanma", "O'quv qo'llanma"), ('Maqola', 'Maqola'), ('Dissertatsiya', 'Dissertatsiya')], default='Kitob', max_length=50, null=True, verbose_name='Resurs Turi'),
        ),
        migrations.AddField(
            model_name='book',
            name='resource_type_uz',
            field=models.CharField(choices=[('Kitob', 'Kitob'), ('Avtoreferat', 'Avtoreferat'), ('Monografiya', 'Monografiya'), ("O'quv qo'llanma", "O'quv qo'llanma"), ('Maqola', 'Maqola'), ('Dissertatsiya', 'Dissertatsiya')], default='Kitob', max_length=50, null=True, verbose_name='Resurs Turi'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects_en',
            field=models.TextField(help_text='Vergul bilan ajratib yozing: Tarix, Roman, Klassika', null=True, verbose_name='Mavzular (Teglar)'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects_ru',
            field=models.TextField(help_text='Vergul bilan ajratib yozing: Tarix, Roman, Klassika', null=True, verbose_name='Mavzular (Teglar)'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects_uz',
            field=models.TextField(help_text='Vergul bilan ajratib yozing: Tarix, Roman, Klassika', null=True, verbose_name='Mavzular (Teglar)'),
        ),
    ]
