# Generated by Django 6.0.2 on 2026-02-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author_en_book_author_ru_book_author_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Adabiyotlar', 'Adabiyotlar'), ('Darslik', 'Darslik'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Barchasi', 'Barchasi')], default='Adabiyotlar', max_length=50, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_en',
            field=models.CharField(choices=[('Adabiyotlar', 'Adabiyotlar'), ('Darslik', 'Darslik'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Barchasi', 'Barchasi')], default='Adabiyotlar', max_length=50, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_ru',
            field=models.CharField(choices=[('Adabiyotlar', 'Adabiyotlar'), ('Darslik', 'Darslik'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Barchasi', 'Barchasi')], default='Adabiyotlar', max_length=50, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_uz',
            field=models.CharField(choices=[('Adabiyotlar', 'Adabiyotlar'), ('Darslik', 'Darslik'), ('Ilmiy', 'Ilmiy Adabiyot'), ('Barchasi', 'Barchasi')], default='Adabiyotlar', max_length=50, null=True, verbose_name='Kategoriya'),
        ),
    ]
