# Generated by Django 6.0.2 on 2026-02-04 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Yangilik', 'Yangilik'), ("E'lon", "E'lon"), ('Tadbir', 'Tadbir'), ('Yangi', 'Yangi'), ('Texnik', 'Texnik'), ('Xizmat', 'Xizmat')], default='Yangilik', max_length=20)),
                ('author', models.CharField(default='Admin', max_length=50)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-date'],
            },
        ),
    ]
