# Generated by Django 6.0.2 on 2026-02-04 18:23

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Admin', max_length=50, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Yangilik', 'Yangilik'), ("E'lon", "E'lon"), ('Tadbir', 'Tadbir'), ('Yangi', 'Yangi'), ('Texnik', 'Texnik'), ('Xizmat', 'Xizmat')], default='Yangilik', max_length=20, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Maqola Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
    ]
