# Generated by Django 6.0.2 on 2026-02-04 18:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_author_alter_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maqola Matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maqola Matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maqola Matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
