# Generated by Django 6.0.2 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_description_en_news_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_en',
            field=models.CharField(default='Admin', max_length=50, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_ru',
            field=models.CharField(default='Admin', max_length=50, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_uz',
            field=models.CharField(default='Admin', max_length=50, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_en',
            field=models.CharField(choices=[('Yangilik', 'Yangilik'), ("E'lon", "E'lon"), ('Tadbir', 'Tadbir'), ('Yangi', 'Yangi'), ('Texnik', 'Texnik'), ('Xizmat', 'Xizmat')], default='Yangilik', max_length=20, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ru',
            field=models.CharField(choices=[('Yangilik', 'Yangilik'), ("E'lon", "E'lon"), ('Tadbir', 'Tadbir'), ('Yangi', 'Yangi'), ('Texnik', 'Texnik'), ('Xizmat', 'Xizmat')], default='Yangilik', max_length=20, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_uz',
            field=models.CharField(choices=[('Yangilik', 'Yangilik'), ("E'lon", "E'lon"), ('Tadbir', 'Tadbir'), ('Yangi', 'Yangi'), ('Texnik', 'Texnik'), ('Xizmat', 'Xizmat')], default='Yangilik', max_length=20, null=True, verbose_name='Kategoriya'),
        ),
    ]
